writting temp hard codes
celo-org/website pull request #362
Opened 2021-09-24 21:35 UTC by Henrynunez112

*Description*
Created the new covers on the public sector on the Government link in the Celor.org site

**Cover**
<img width="1412" alt="Screen Shot 2021-09-24 at 5 32 00 PM" src="https://user-images.githubusercontent.com/55670305/134742050-19feb199-a42e-4924-98dd-e8ee3614dba5.png">

**Public Sector**
<img width="1304" alt="Screen Shot 2021-09-24 at 5 33 09 PM" src="https://user-images.githubusercontent.com/55670305/134742099-84b69b99-a06b-43dd-876e-70f778c7f597.png">

issue #326

2021-09-24 21:40 UTC, aaronmgdr requested changes
I cant approve this. basing logic off the text of the title will make this way to brittle.

2021-09-24 22:22 UTC, aaronmgdr commented on src/contentful/grid2-cells/Heading.tsx
> +        props.title === "Public Sector on Celo" ?
gotta fix this too

2021-09-24 22:33 UTC, aaronmgdr commented on src/contentful/grid2-cells/Heading.tsx
> +  console.log(props, "<---- this is props")
remove

2021-09-24 22:34 UTC, aaronmgdr commented on src/contentful/grid2-cells/Heading.tsx
> +        props.newIcon ?
does newIcon exist here?

2021-09-24 22:46 UTC, Henrynunez112 commented on src/contentful/grid2-cells/Heading.tsx
> +        props.newIcon ?
yeah

2021-09-27 16:59 UTC, aaronmgdr commented on src/contentful/grid2-cells/Blurb.tsx
> +}
can you format this?

2021-09-27 17:00 UTC, aaronmgdr commented on src/contentful/grid2-cells/Blurb.tsx
> +}
super nit i know

2021-09-27 17:31 UTC, Henrynunez112 commented on src/contentful/grid2-cells/Blurb.tsx
> +}
yessir

2021-09-27 21:22 UTC, aaronmgdr approved these changes

2021-09-27 23:32 UTC, merged