first draft
celo-org/website pull request #555
Opened 2022-01-26 18:56 UTC by Henrynunez112

**Description**

First Draft of the widget state (still needs a mobile version)

<img width="1251" alt="Screen Shot 2022-01-26 at 1 07 04 PM" src="https://user-images.githubusercontent.com/55670305/151228260-b4b34c0f-fbcd-4e73-bb36-e16a0927ae18.png">

2022-01-26 22:36 UTC, aaronmgdr commented on src/home/stats/Stats.tsx
> +  ["@media (max-width: 1165px)"]: {
can you use one of our standard `WHEN_*` constants here? and in other similar places?

2022-01-26 22:38 UTC, aaronmgdr commented on src/home/stats/Stats.tsx
> +    height: 222,
really not a good idea to set both width and height of something containing text.so many ways for that to get messed up. 

Example
* different language
* numbers get bigger
* px density or someone manuall resizes tx

2022-01-26 22:39 UTC, aaronmgdr commented on src/home/stats/Stats.tsx
> +    height: 222,
better practice is to set neight an reliy on padding alone to get to a implicit size

2022-01-26 22:39 UTC, aaronmgdr requested changes
see other comments

2022-01-26 22:44 UTC, Henrynunez112 commented on src/home/stats/Stats.tsx
> +    height: 222,
So many factors to think about!

2022-01-27 17:31 UTC, aaronmgdr commented on src/home/stats/Stats.tsx
> +    paddingBottom: 222,
wow thats a lot

2022-01-27 17:35 UTC, aaronmgdr commented on src/home/stats/Stats.tsx
> +  height: 116,
set a max width and remove height and width.

2022-01-27 21:22 UTC, aaronmgdr approved these changes

2022-01-27 21:37 UTC, merged